# Python
I am trying to connect LTE dongle (locked and unlocked version) with Raspberry pi3. We are facing issue in this as we are quite na√Øve in working with LINUX operating system. We have done all troubleshooting from our end. I am attaching the snapshot of the error that we are getting.Attaching the picture of error message along. Steps that we have followed while doing this:
